{% set name = "storefact" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2140655072b30e5feb1e5a78e667c2c03c791812cc22aed771fbcc9d346bc828

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - simplekv
    - toolz
    - uritools

test:
  imports:
    - storefact

about:
  home: https://github.com/blue-yonder/storefact
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A factory for simplekv-Store-based storage classes.
  dev_url: https://github.com/blue-yonder/storefact

extra:
  recipe-maintainers:
    - xhochy
