travis:
  secure:
    BINSTAR_TOKEN: RgQjAsvYMJJ4t+sTbqKqY0frYzon286eycNPk7jYTCY6Prpa8b6ttoF8a6gJHmSW3cFr8TX3+pT94RcewlQf/C+Ymn1+HOngXGlqqRG4mnbta2rYNVn4TiJegzwd9tJThXW04TZqBx+e7zF+lWunskEaMONXDlkuu9AgvaPKPHHTDJPMMJ//D7rr1cbbo5qbDlT49oBpzBusT4uYO4Z8BgtTSoQLBr7wN8ILFHdzPSmk1Yj1Iblr35o8EGZugcMglOR+EF9aMjWIk2RdVtm2QNMXwuCGiw868Sl3qpWMer76oh2SPntwQIAY9YhaSGsnbuESacqGAfM/08x3W8z/QaB35a67XLe5sirp4vWYZIB+hclcNyCM6KsQfh6iaYufnkLgMCmIhCqVMc52Z7NXI2Ads6Sy7ttPzaMe+xxGaviJoVdaEYBRzbqk3wPJb6Gq1zuctLNXjPl6AiAXyVDgoD7TxUcKrifewoRswOSlmTBqSRegsvAl2gB504BLV7KMWqO4BEj2/W2foQ0fxO7R/+wYhRSIn5CmDqAtxCfuxTJrRNL8h8ldx4fBEpRxGSjdg2PrEsc5Q6oOBtaSOXWyRYxP6vGxcEb82swq4iCOc0TdQnhcy7YgNvUe/I/8bhrWwjB4CT4PvN4XUNWWGIQj5mnjNfqFDVE56wSTPCqIjlo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
